---
title: "R Notebook"
output: html_notebook
---

```{r, echo=FALSE}
# load needed packages
library(MASS)
library(smacof)
library(cluster)
library(fossil)
library(latex2exp)
```

```{r}
# time points for simulation
ts <- 0.1 
tps <- seq(0, 0.3, by=ts) 
l <- length(tps) 

# no. of nodes, dimensions and clusters
n <- 5
d <- 2 
L <- 2 

# parameters for kernel function
alpha1 <- 8
ro1 <- 1
paras1 <- c(alpha1, ro1)
alpha2 <- 2
ro2 <- 0.5
paras2 <- c(alpha2, ro2)
```

```{r}
# squared exponential kernel function
k_sqexp <- function(t1, t2, paras){
  alpha <- paras[1]
  ro <- paras[2]
  alpha^2 * exp(-0.5 * abs(t1-t2)^2 / ro^2)
}

# extract positive part of a vector
f2 <- function(x){
  pmax(x, 0)
}

# generate mean of gaussian process according to cluster
gen_mu <- function(tps, d, paras, m, k){
  l <- length(tps)
  K <- matrix(NA, l, l)
  for (i in 1:l){
    for (j in 1:l){
      K[i, j] <- k(tps[i], tps[j], paras)
    }
  }
  mvrnorm(d, rep(m, l), K)
}

# generate latent positions of each node 
gen_x <- function(tps, paras, m, f, k){
  l <- length(tps)
  d <- dim(m)[1]
  K <- matrix(NA, l, l)
  x <- matrix(NA, d, l)
  for (i in 1:l){
    for (j in 1:l){
      K[i, j] <- k(tps[i], tps[j], paras)
    }
  }
  for (i in 1:d){
    x[i,] <- f(mvrnorm(1, m[i,], K))
  }
  x
}

# generate SOC between each pair of nodes
gen_lambda <- function(tps, paras, mus, grps, f, k){
  ts <- tps[2] - tps[1]
  n <- length(grps)
  l <- length(tps)
  d <- dim(mus)[1]
  lambda <- array(NA, c(n, n, l))
  x <- f(mvrnorm(d, rep(1, n), 0.16*diag(n)))
  ys <- array(NA, c(d, l, n))
  for (i in 1:n){
    ys[,,i] <- gen_x(tps, paras, mus[,,grps[i]], f, k)
  }
  ys <- aperm(ys, c(1, 3, 2))
  for (i in 1:l){
    y <- ys[,,i]
    lambda[,,i] <- t(x) %*% y
  }
  list(x=x, y=t(matrix(ys, c(d, n*l))), ys=ys, lambda=lambda)
}

# simulate poisson process
sim_pois <- function(tps, n, lambda){
  ts <- tps[2] - tps[1]
  l <- length(tps)
  Ai <- array(NA, c(n, n, l))
  Ac <- array(NA, c(n, n, l))
  Ai[,,1] <- matrix(rpois(n^2, lambda[,,1]*ts), nrow=n, byrow=FALSE)
  Ac[,,1] <- Ai[,,1]
  for (i in 2:l){
    Ai[,,i] <- matrix(rpois(n^2, lambda[,,i]*ts), nrow=n, byrow=FALSE)
    Ac[,,i] <- Ac[,,i-1] + Ai[,,i]
  }
  list(Ai=Ai, Ac=Ac)
}

# IUASE
decompose <- function(A_arr, nd){
  n <- dim(A_arr)[1]
  l <- dim(A_arr)[3]
  A <- matrix(A_arr, n, n*l)
  udv <- svd(A, nd, nd)
  u <- udv$u
  d <- (udv$d)[1:nd]
  v <- udv$v
  x <- u %*% diag(sqrt(d))
  y <- v %*% diag(sqrt(d))
  ys <- array(t(y), c(nd, n, l))
  Ah <- x %*% t(y)
  Ash <- array(Ah, c(n, n, l))
  list(x=x, y=y, ys=ys, Ash=Ash)
}

# ASE
decompose_ase <- function(A, nd){
  n <- dim(A)[1]
  udv <- svd(A, nd, nd)
  u <- udv$u
  d <- (udv$d)[1:nd]
  v <- udv$v
  x <- u %*% diag(sqrt(d))
  y <- v %*% diag(sqrt(d))
  Ah <- x %*% t(y)
  list(x=x, y=y, Ah=Ah)
}

# SASE
decompose_sase <- function(A_arr, nd){
  n <- dim(A_arr)[1]
  l <- dim(A_arr)[3]
  x <- array(NA, c(n, nd, l))
  y <- array(NA, c(n, nd, l))
  Ash <- array(NA, c(n, n, l))
  for (i in 1:l) {
    A <- A_arr[,,i]
    xyi <- decompose_ase(A, nd)
    x[,,i] <- xyi$x
    y[,,i] <- xyi$y
    Ash[,,i] <- xyi$Ah
  }
  xs <- aperm(x, c(2, 1, 3))
  ys <- aperm(y, c(2, 1, 3))
  list(xs=xs, ys=ys, Ash=Ash)
}

# OE
decompose_omnibus <- function(A_arr, nd){
  n <- dim(A_arr)[1]
  l <- dim(A_arr)[3]
  A <- matrix(NA, n*l, n*l)
  for (i in 1:l){
    for (j in 1:l){
      A[(n*(i-1)+1):(n*i), (n*(j-1)+1):(n*j)] <- (A_arr[,,i]+A_arr[,,j]) / 2
    }
  }
  udv <- svd(A, nd, nd)
  u <- udv$u
  d <- (udv$d)[1:nd]
  v <- udv$v
  x <- u %*% diag(sqrt(d))
  y <- v %*% diag(sqrt(d))
  xs <- array(t(x), c(nd, n, l))
  ys <- array(t(y), c(nd, n, l))
  Ash <- array(NA, c(n, n, l))
  for (i in 1:l) {
    Ash[,,i] <- x[((n*(i-1)+1):(n*i)),] %*% 
      t(y[((n*(i-1)+1):(n*i)),])
  }
  list(xs=xs, ys=ys, Ash=Ash)
}

# approximate derivatives 
dif <- function(dx, y){
  d <- dim(y)[1]
  n <- dim(y)[2]
  l <- dim(y)[3]
  yp <- array(NA, c(d, n, l))
  yp[,,1] <- y[,,1] / dx
  for (i in 2:l){
    yp[,,i] <- (y[,,i]-y[,,(i-1)]) / dx
  }
  yp
}

# mean squared errors
mse <- function(lambdas, lambdahs){
  mean((lambdas - lambdahs)^2)
}

# procrustes transformation
proc <- function(X, Y){
  p <- Procrustes(X, Y)
  rt <- p$rotation
  dl <- p$dilation
  list(rt=rt, dl=dl, Yhat=dl * Y %*% rt)
}
```

```{r}
# generate SOC for all pairs of nodes and all time points
set.seed(123)
grps <- sample(1:L, n, TRUE, rep(1/L, L))
mus <- array(NA, c(d, l, L))
mus[,,1] <- gen_mu(tps, d, paras1, 12, k_sqexp)
mus[,,2] <- gen_mu(tps, d, paras1, 15, k_sqexp)
lambda_arr <- gen_lambda(tps, paras2, mus, grps, f2, k_sqexp)$lambda
```

```{r}
# conduct simulation
set.seed(321)
simulation <- sim_pois(tps, n, lambda_arr)
Ai_arr <- simulation$Ai
Ac_arr <- simulation$Ac
```

```{r}
# obtain embeddings
xy_ase <- decompose_ase(Ai_arr[,,1], d)
xy_sase <- decompose_sase(Ai_arr, d)
x_sase <- xy_sase$xs
y_sase <- array(NA, c(d, n, l))
for (j in 1:l){
  p <- proc(t(x_sase[,,1]), t(x_sase[,,j]))
  rt <- p$rt
  dl <- p$dl
  y_sase[,,j] <- t(rt) %*% xy_sase$ys[,,j] / dl
}
y_sase <- t(matrix(y_sase, c(d, n*l)))
xy_iuase <- decompose(Ai_arr, d)
xy_cuase <- decompose(Ac_arr, d)
xy_cuase$ys <- dif(1, xy_cuase$ys)
xy_oe <- decompose_omnibus(Ai_arr, d)
```

```{r}
# plot of motivating example
colors <- c("#EE8434", "#0F7173", "#C95D63", "#95BF8F", "#717EC3")
plot(xy_ase$x[,1], xy_ase$x[,2], col=colors, cex=3, pch=19, type="p",
     xlim=c(-4, 0), ylim=c(-2, 1), xlab="", ylab="", 
     xaxp=c(-4, 0, 4), yaxp=c(-2, 1, 3))
text(xy_ase$x[,1], xy_ase$x[,2], labels=1:n, col="white", cex=1.2)

plot(xy_ase$y[,1], xy_ase$y[,2], col=colors, cex=3, pch=19, type="p",
     xlim=c(-4, 0), ylim=c(-2, 1), xlab="", ylab="", 
     xaxp=c(-4, 0, 4), yaxp=c(-2, 1, 3))
text(xy_ase$y[,1], xy_ase$y[,2], labels=1:n, col="white", cex=1.2)
```

```{r}
# example 2
plot(y_sase[1:5,1], y_sase[1:5,2], col=colors, cex=3, pch=19, type="p",
     xlim=c(-4, 0), ylim=c(-4, 1), xlab="", ylab="",
     xaxp=c(-4, 0, 4), yaxp=c(-4, 1, 5))
text(y_sase[1:5,1], y_sase[1:5,2], labels=1:n, col="white", cex=1.2)
for (i in 2:l){
  plot(y_sase[(i-1)*5+1:5,1], y_sase[(i-1)*5+1:5,2], col=colors, cex=3, pch=19, type="p",
       xlim=c(-4, 0), ylim=c(-4, 1), xlab="", ylab="",
       xaxp=c(-4, 0, 4), yaxp=c(-4, 1, 5))
  text(y_sase[(i-1)*5+1:5,1], y_sase[(i-1)*5+1:5,2], labels=1:n, col="white", cex=1.2)
}
```

```{r}
# example 3
plot(xy_iuase$ys[1,,1], xy_iuase$ys[2,,1], col=colors, cex=3, pch=19, type="p",
     xlim=c(-3, 0), ylim=c(-2, 2), xlab="", ylab="",
     xaxp=c(-3, 0, 3), yaxp=c(-2, 2, 4))
text(xy_iuase$ys[1,,1], xy_iuase$ys[2,,1], labels=1:n, col="white", cex=1.2)
for (i in 2:l){
  plot(xy_iuase$ys[1,,i], xy_iuase$ys[2,,i], col=colors, cex=3, pch=19, type="p",
       xlim=c(-3, 0), ylim=c(-2, 2), xlab="", ylab="",
     xaxp=c(-3, 0, 3), yaxp=c(-2, 2, 4))
  text(xy_iuase$ys[1,,i], xy_iuase$ys[2,,i], labels=1:n, col="white", cex=1.2)
}
```

```{r}
# example 4
plot(xy_cuase$ys[1,,1], xy_cuase$ys[2,,1], col=colors, cex=3, pch=19, type="p",
     xlim=c(-2, 0), ylim=c(-2, 2), xlab="", ylab="",
     xaxp=c(-2, 0, 2), yaxp=c(-2, 2, 4))
text(xy_cuase$ys[1,,1], xy_cuase$ys[2,,1], labels=1:n, col="white", cex=1.2)
for (i in 2:l){
  plot(xy_cuase$ys[1,,i], xy_cuase$ys[2,,i], col=colors, cex=3, pch=19, type="p",
     xlim=c(-2, 0), ylim=c(-2, 2), xlab="", ylab="",
     xaxp=c(-2, 0, 2), yaxp=c(-2, 2, 4))
  text(xy_cuase$ys[1,,i], xy_cuase$ys[2,,i], labels=1:n, col="white", cex=1.2)
}
```

```{r}
# example 5
plot(xy_oe$xs[1,,1], xy_oe$xs[2,,1], col=colors, cex=3, pch=19, type="p",
     xlim=c(-3, 0), ylim=c(-2, 2), xlab="", ylab="",
     xaxp=c(-3, 0, 3), yaxp=c(-2, 2, 4))
text(xy_oe$xs[1,,1], xy_oe$xs[2,,1], labels=1:n, col="white", cex=1.2)
for (i in 2:l){
  plot(xy_oe$xs[1,,i], xy_oe$xs[2,,i], col=colors, cex=3, pch=19, type="p",
     xlim=c(-3, 0), ylim=c(-2, 2), xlab="", ylab="",
     xaxp=c(-3, 0, 3), yaxp=c(-2, 2, 4))
  text(xy_oe$xs[1,,i], xy_oe$xs[2,,i], labels=1:n, col="white", cex=1.2)
}

plot(xy_oe$ys[1,,1], xy_oe$ys[2,,1], col=colors, cex=3, pch=19, type="p",
     xlim=c(-3, 0), ylim=c(-2, 2), xlab="", ylab="",
     xaxp=c(-3, 0, 3), yaxp=c(-2, 2, 4))
text(xy_oe$ys[1,,1], xy_oe$ys[2,,1], labels=1:n, col="white", cex=1.2)
for (i in 2:l){
  plot(xy_oe$ys[1,,i], xy_oe$ys[2,,i], col=colors, cex=3, pch=19, type="p",
     xlim=c(-3, 0), ylim=c(-2, 2), xlab="", ylab="",
     xaxp=c(-3, 0, 3), yaxp=c(-2, 2, 4))
  text(xy_oe$ys[1,,i], xy_oe$ys[2,,i], labels=1:n, col="white", cex=1.2)
}
```





